//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Aerofoil.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDS_PHYSICAL_MEM             102
#define CG_IDS_DISK_SPACE               103
#define CG_IDS_DISK_SPACE_UNAVAIL       104
#define IDB_SPLASH                      105
#define IDR_MAINFRAME                   128
#define IDR_AEROFOTYPE                  129
#define IDD_SECTION_POS                 130
#define IDR_CUTTERTYPE                  130
#define IDD_EDIT_WING                   131
#define IDD_EDIT_SECTION                132
#define IDD_WING_FLAGS                  133
#define IDD_EDIT_SPAR                   134
#define IDD_ZOOM                        135
#define IDD_PAGE_SIZE                   136
#define IDD_SELECT_WING                 137
#define IDD_SELECT_STRUCTURE            137
#define IDD_ELLIPSE_PAIR                138
#define IDR_WING_FLOATING               139
#define IDR_ELLIPSE_FLOATING            140
#define IDD_PLOT_FLAGS                  141
#define IDR_PLOTPOINT_FLOATING          142
#define IDD_PLOT_POINT                  143
#define IDD_PLOT_ORDER                  144
#define IDD_CNC_CONNECTION              145
#define IDD_ELLIPSE_FLAGS               146
#define IDD_BACKGROUND_GRID             148
#define IDR_CUTTER_POPUPS               149
#define IDD_CUT_TRANSFORM               153
#define IDD_GCODE_EDIT                  155
#define IDD_WING_CUT_FLAGS              156
#define IDD_TOOL_OFFSET                 158
#define IDD_FEED_RATE                   160
#define IDD_EDIT_CUTOUT                 162
#define IDC_EDT_POSITION                1000
#define IDC_EDT_SPAN                    1001
#define IDC_EDT_LE                      1002
#define IDC_EDT_TE                      1003
#define IDC_CMD_ROOT_EDIT               1004
#define IDC_CMD_TIP_EDIT                1005
#define IDC_LBL_ROOT_INFO               1006
#define IDC_LBL_TIP_INFO                1007
#define IDC_CMD_ADD_SPAR                1008
#define IDC_CMD_SPAR_EDIT               1009
#define IDC_CMD_SPAR_DELETE             1010
#define IDC_LST_SPARS                   1011
#define IDC_LBL_SECTION_NAME            1012
#define IDC_EDT_SKIN                    1012
#define IDC_CMD_SECTION_NAME            1013
#define IDC_EDT_CHORD                   1014
#define IDC_EDT_SWEEP                   1015
#define IDC_CHK_PLOT_CHORD              1015
#define IDC_EDT_HEIGHT                  1016
#define IDC_CHK_PLOT_INVERTED           1016
#define IDC_EDT_WASHOUT                 1017
#define IDC_CHK_PLOT_LABELS             1017
#define IDC_EDT_THICKNESS_MOD           1018
#define IDC_CHK_PLOT_LE                 1018
#define IDC_CHK_PLOT_TE                 1019
#define IDC_CHK_PLOT_MARKERS            1020
#define IDC_CHK_PLOT_SECTION            1021
#define IDC_CHK_PLOT_SKIN               1022
#define IDC_CHK_PLOT_SPARS              1023
#define IDC_CHK_SUBMERGED               1024
#define IDC_RAD_TOP                     1025
#define IDC_RAD_BOTTOM                  1026
#define IDC_RAD_FULL_DEPTH              1027
#define IDC_EDT_ROOT_X                  1028
#define IDC_EDT_ROOT_WIDTH              1029
#define IDC_EDT_ROOT_HEIGHT             1030
#define IDC_RADZOOM200                  1030
#define IDC_EDT_TIP_X                   1031
#define IDC_RAD_ZOOM100                 1031
#define IDC_EDT_TIP_WIDTH               1032
#define IDC_RADZOOM25                   1032
#define IDC_EDT_TIP_HEIGHT              1033
#define IDC_RADZOOMFIT                  1033
#define IDC_RADZOOM50                   1034
#define IDC_RAD_A4                      1035
#define IDC_RAD_A4L                     1036
#define IDC_RAD_A3                      1037
#define IDC_RAD_A3L                     1038
#define IDC_RAD_CUSTOM                  1039
#define IDC_EDT_WIDTH                   1040
#define IDC_LST_WINGS                   1042
#define IDC_EDT_FIRST_A_BOTTOM          1043
#define IDC_EDT_FIRST_A_TOP             1044
#define ID_COPY                         1044
#define IDC_EDT_FIRST_B                 1045
#define IDC_EDT_FIRST_X                 1046
#define IDC_EDT_FIRST_Y                 1047
#define IDC_EDT_SECOND_A_TOP            1048
#define IDC_EDT_SECOND_A_BOTTOM         1049
#define IDC_EDT_SECOND_B                1050
#define IDC_EDT_SECOND_X                1051
#define IDC_EDT_SECOND_Y                1052
#define IDC_COPY                        1053
#define IDC_CHK_INVERT                  1054
#define IDC_CHK_REFLECT                 1055
#define IDC_RAD_LEFT                    1056
#define IDC_RADIO2                      1057
#define IDC_EDT_ROOT_Y                  1059
#define IDC_EDT_TIP_Y                   1061
#define IDC_CMD_COPY                    1064
#define IDC_LST_STRUCTURES              1065
#define IDC_CMD_UP                      1066
#define IDC_CMD_TOP                     1067
#define IDC_CMD_DOWN                    1068
#define IDC_EDT_HOST                    1068
#define IDC_CMD_BOTTOM                  1069
#define IDC_EDT_PORT                    1069
#define IDC_LBL_VER                     1070
#define IDC_LBL_COPYRIGHT               1071
#define IDC_PHYSICAL_MEM                1072
#define IDC_DISK_SPACE                  1073
#define IDC_CHK_PLOT_UPPER              1074
#define IDC_CHK_PLOT_LOWER              1075
#define IDC_CHK_HORIZ                   1077
#define IDC_EDT_HORIZ_MM                1078
#define IDC_RAD_HORIZ_3                 1079
#define IDC_RAD_HORIZ_ANY               1080
#define IDC_RAD_HORIZ_4                 1081
#define IDC_CHK_VERT                    1082
#define IDC_EDT_ROOT_XOFFSET            1082
#define IDC_EDT_VERT_MM                 1083
#define IDC_EDT_ROOT_YOFFSET            1083
#define IDC_RAD_VERT_3                  1084
#define IDC_EDT_TIP_XOFFSET             1084
#define IDC_RAD_VERT_4                  1085
#define IDC_EDT_TIP_YOFFSET             1085
#define IDC_RAD_VERT_ANY                1086
#define IDC_BTN_COPY                    1086
#define IDC_EDT_GCODE                   1087
#define IDC_EDT_ERROR                   1088
#define IDC_CHK_CUT_LE                  1089
#define IDC_CHK_CUT_TE                  1090
#define IDC_CHK_CUT_SPARS               1091
#define IDC_EDIT_TOOL_OFFSET            1092
#define IDC_CHK_CUT_SPARS2              1092
#define IDC_CHK_CUT_CUTOUTS             1092
#define IDC_EDIT1                       1093
#define IDC_EDIT_FEED_RATE              1093
#define IDC_CHECK1                      1094
#define IDC_CHK_INCLUDE_FEED            1094
#define IDC_CHK_TOP_SURFACE             1094
#define IDC_CHK_PLOT_CUTOUTS            1094
#define IDC_CHK_CENTRE                  1095
#define IDC_LST_CUTOUTS                 1099
#define IDC_BTN_ADD_CUTOUT              1100
#define IDC_BTN_EDIT_CUTOUT             1101
#define IDC_BTN_DELETE_CUTOUT           1102
#define ID_WING_NEW                     32771
#define ID_WING_NEW_SECTION             32772
#define ID_WING_NEW_CORE                32773
#define ID_WING_FLAGS                   32774
#define ID_WING_SELECT                  32775
#define ID_WING_EDIT                    32776
#define ID_VIEW_ZOOM                    32777
#define ID_FILE_PLOT_SIZE               32778
#define ID_ELLIPSE_NEW                  32779
#define ID_ELLIPSE_SELECT               32780
#define ID_ELLIPSE_NEW_SECTION          32781
#define ID_ELLIPSE_EDIT                 32782
#define ID_ELLIPSE_FLAGS                32783
#define ID_FILE_DXF                     32784
#define ID_FILE_POSTSCRIPT              32785
#define ID_FILE_LASERJET                32786
#define ID_POPUP_WING_EDIT              32787
#define ID_POPUP_WING_POSITION          32788
#define ID_POPUP_EDIT_WING              32789
#define ID_POPUP_WING_SET_POSITION      32790
#define ID_POPUP_WING_SELECT            32791
#define ID__DELETE                      32792
#define ID_POPUP_WING_DELETE            32793
#define ID__EDIT                        32794
#define ID_POPUP_ELLIPSE_EDIT           32795
#define ID_POPUP_ELLIPSE_DELETE         32796
#define ID_POPUP_ELLIPSE_POSITION       32797
#define ID_EDIT_POSITION                32798
#define ID_EDIT_DELETE                  32799
#define ID_EDIT_STRUCTURE               32800
#define ID_VIEW_PREVIEW_CUT_PATH        32801
#define ID_EDIT_PLOTFLAGS               32802
#define ID_EDIT_SELECTSTRUCTURE         32803
#define ID_POINT_NEW                    32805
#define ID_POINT_SILENT                 32806
#define ID_EDIT_PLOTORDER               32807
#define ID_FILE_CNCSETUP                32808
#define ID_FILE_CNCOUTPUT               32809
#define ID_POINT_EDIT                   32810
#define ID_EDIT_DELETESTRUCTURE         32811
#define ID_EDIT_PLOT_FLAGS              32813
#define ID_FILE_SETGRID                 32814
#define ID_Menu                         32815
#define ID_GCODEOUTPOUT_ID              32816
#define ID_FILE_GCODE                   32817
#define ID_STRUCTURE_NEWWING            32818
#define ID_STRUCTURE_NEWELLIPSE         32819
#define ID_STRUCTURE_NEWPOINT           32820
#define ID_CUTTING_CORE                 32821
#define ID_CUTTING_ELLIPSE              32822
#define ID_CUTTING_POINT                32823
#define ID_CUTTING_G                    32824
#define ID_CUTTING_DXF                  32825
#define ID_CUTTING_HOME                 32826
#define ID_CUTTING_GCODE                32827
#define ID_WING_EDIT32828               32828
#define ID_WING_DELETE                  32829
#define ID_ELLIPSE_EDIT32830            32830
#define ID_ELLIPSE_DELETE               32831
#define ID_POINT_EDIT32832              32832
#define ID_POINT_DELETE                 32833
#define ID_Menu32834                    32834
#define ID_WING_NEWCORE                 32835
#define ID_ELLIPSE_NEWCUT               32836
#define ID_POINT_NEWCUT                 32837
#define ID_DXF_NEWCUT                   32838
#define ID_DXF_DELETE                   32839
#define ID_GCODE_EDIT                   32840
#define ID_GCODE_NEWCUT                 32841
#define ID_GCODE_DELETE                 32842
#define ID_WINGCUT_EDIT                 32843
#define ID_WINGCUT_D                    32844
#define ID_ELLIPSECUT_EDIT              32845
#define ID_ELLIPSECUT_DELETE            32846
#define ID_POINTCUT_EDIT                32847
#define ID_POINTCUT_DELETE              32848
#define ID_GCODECUT_EDIT                32849
#define ID_GCODECUT_DELETE              32850
#define ID_DXFCUT_EDIT                  32851
#define ID_DXFCUT_DELETE                32852
#define ID_HOMECUT_DELETE               32853
#define ID_STRUCTURE_NEWGCODE           32854
#define ID_STRUCTURE_NEWDXF             32855
#define ID_WINGCUT_MOVEUP               32856
#define ID_WINGCUT_MOVEDOWN             32857
#define ID_ELLIPSECUT_MOVEUP            32858
#define ID_ELLIPSECUT_MOVEDOWN          32859
#define ID_POINTCUT_MOVEUP              32860
#define ID_POINTCUT_MOVEDOWN            32861
#define ID_GCODECUT_MOVEUP              32862
#define ID_GCODECUT_MOVEDOWN            32863
#define ID_DXFCUT_MOVEUP                32864
#define ID_DXFCUT_MOVEDOWN              32865
#define ID_HOMECUT_MOVEUP               32866
#define ID_HOMECUT_MOVEDOWN             32867
#define ID_CUT_MOVEUP                   32868
#define ID_CUT_MOVEDOWN                 32869
#define ID_WINGCUT_TRANSFORM            32870
#define ID_CUT_TRANSFORM                32871
#define ID_ELLIPSECUT_TRANSFORM         32872
#define ID_POINTCUT_TRANSFORM           32873
#define ID_VIEW_DRAWMOVES               32874
#define ID_WING_PLOTFLAGS               32875
#define ID_POINT_NEWMOVE                32876
#define ID_POINTCUT_MAKECUT             32877
#define ID_POINTCUT_MAKEMOVE            32878
#define ID_CUTTER_TOOLOFFSET            32879
#define ID_CUTTER_FEEDRATE              32880

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
