//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Aerofoil.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDS_PHYSICAL_MEM             102
#define CG_IDS_DISK_SPACE               103
#define CG_IDS_DISK_SPACE_UNAVAIL       104
#define IDB_SPLASH                      105
#define IDR_MAINFRAME                   128
#define IDR_AEROFOTYPE                  129
#define IDD_SECTION_POS                 130
#define IDD_EDIT_WING                   131
#define IDD_EDIT_SECTION                132
#define IDD_WING_FLAGS                  133
#define IDD_EDIT_SPAR                   134
#define IDD_ZOOM                        135
#define IDD_PAGE_SIZE                   136
#define IDD_SELECT_WING                 137
#define IDD_SELECT_STRUCTURE            137
#define IDD_ELLIPSE_PAIR                138
#define IDR_WING_FLOATING               139
#define IDR_ELLIPSE_FLOATING            140
#define IDD_PLOT_FLAGS                  141
#define IDR_PLOTPOINT_FLOATING          142
#define IDD_PLOT_POINT                  143
#define IDD_PLOT_ORDER                  144
#define IDD_CNC_CONNECTION              145
#define IDD_ELLIPSE_FLAGS               146
#define IDD_BACKGROUND_GRID             148
#define IDC_EDT_POSITION                1000
#define IDC_EDT_SPAN                    1001
#define IDC_EDT_LE                      1002
#define IDC_EDT_TE                      1003
#define IDC_CMD_ROOT_EDIT               1004
#define IDC_CMD_TIP_EDIT                1005
#define IDC_LBL_ROOT_INFO               1006
#define IDC_LBL_TIP_INFO                1007
#define IDC_CMD_ADD_SPAR                1008
#define IDC_CMD_SPAR_EDIT               1009
#define IDC_CMD_SPAR_DELETE             1010
#define IDC_LST_SPARS                   1011
#define IDC_LBL_SECTION_NAME            1012
#define IDC_EDT_SKIN                    1012
#define IDC_CMD_SECTION_NAME            1013
#define IDC_EDT_CHORD                   1014
#define IDC_EDT_SWEEP                   1015
#define IDC_CHK_PLOT_CHORD              1015
#define IDC_EDT_HEIGHT                  1016
#define IDC_CHK_PLOT_INVERTED           1016
#define IDC_EDT_WASHOUT                 1017
#define IDC_CHK_PLOT_LABELS             1017
#define IDC_EDT_THICKNESS_MOD           1018
#define IDC_CHK_PLOT_LE                 1018
#define IDC_CHK_PLOT_TE                 1019
#define IDC_CHK_PLOT_MARKERS            1020
#define IDC_CHK_PLOT_SECTION            1021
#define IDC_CHK_PLOT_SKIN               1022
#define IDC_CHK_PLOT_SPARS              1023
#define IDC_CHK_SUBMERGED               1024
#define IDC_RAD_TOP                     1025
#define IDC_RAD_BOTTOM                  1026
#define IDC_RAD_FULL_DEPTH              1027
#define IDC_EDT_ROOT_X                  1028
#define IDC_EDT_ROOT_WIDTH              1029
#define IDC_EDT_ROOT_HEIGHT             1030
#define IDC_RADZOOM200                  1030
#define IDC_EDT_TIP_X                   1031
#define IDC_RAD_ZOOM100                 1031
#define IDC_EDT_TIP_WIDTH               1032
#define IDC_RADZOOM25                   1032
#define IDC_EDT_TIP_HEIGHT              1033
#define IDC_RADZOOMFIT                  1033
#define IDC_RADZOOM50                   1034
#define IDC_RAD_A4                      1035
#define IDC_RAD_A4L                     1036
#define IDC_RAD_A3                      1037
#define IDC_RAD_A3L                     1038
#define IDC_RAD_CUSTOM                  1039
#define IDC_EDT_WIDTH                   1040
#define IDC_LST_WINGS                   1042
#define IDC_EDT_FIRST_A_BOTTOM          1043
#define IDC_EDT_FIRST_A_TOP             1044
#define ID_COPY                         1044
#define IDC_EDT_FIRST_B                 1045
#define IDC_EDT_FIRST_X                 1046
#define IDC_EDT_FIRST_Y                 1047
#define IDC_EDT_SECOND_A_TOP            1048
#define IDC_EDT_SECOND_A_BOTTOM         1049
#define IDC_EDT_SECOND_B                1050
#define IDC_EDT_SECOND_X                1051
#define IDC_EDT_SECOND_Y                1052
#define IDC_COPY                        1053
#define IDC_CHK_INVERT                  1054
#define IDC_CHK_REFLECT                 1055
#define IDC_RAD_LEFT                    1056
#define IDC_RADIO2                      1057
#define IDC_EDT_ROOT_Y                  1059
#define IDC_EDT_TIP_Y                   1061
#define IDC_CMD_COPY                    1064
#define IDC_LST_STRUCTURES              1065
#define IDC_CMD_UP                      1066
#define IDC_CMD_TOP                     1067
#define IDC_CMD_DOWN                    1068
#define IDC_EDT_HOST                    1068
#define IDC_CMD_BOTTOM                  1069
#define IDC_EDT_PORT                    1069
#define IDC_LBL_VER                     1070
#define IDC_LBL_COPYRIGHT               1071
#define IDC_PHYSICAL_MEM                1072
#define IDC_DISK_SPACE                  1073
#define IDC_CHK_PLOT_UPPER              1074
#define IDC_CHK_PLOT_LOWER              1075
#define IDC_CHK_HORIZ                   1077
#define IDC_EDT_HORIZ_MM                1078
#define IDC_RAD_HORIZ_3                 1079
#define IDC_RAD_HORIZ_ANY               1080
#define IDC_RAD_HORIZ_4                 1081
#define IDC_CHK_VERT                    1082
#define IDC_EDT_VERT_MM                 1083
#define IDC_RAD_VERT_3                  1084
#define IDC_RAD_VERT_4                  1085
#define IDC_RAD_VERT_ANY                1086
#define ID_WING_NEW                     32771
#define ID_WING_NEW_SECTION             32772
#define ID_WING_NEW_CORE                32773
#define ID_WING_FLAGS                   32774
#define ID_WING_SELECT                  32775
#define ID_WING_EDIT                    32776
#define ID_VIEW_ZOOM                    32777
#define ID_FILE_PLOT_SIZE               32778
#define ID_ELLIPSE_NEW                  32779
#define ID_ELLIPSE_SELECT               32780
#define ID_ELLIPSE_NEW_SECTION          32781
#define ID_ELLIPSE_EDIT                 32782
#define ID_ELLIPSE_FLAGS                32783
#define ID_FILE_DXF                     32784
#define ID_FILE_POSTSCRIPT              32785
#define ID_FILE_LASERJET                32786
#define ID_POPUP_WING_EDIT              32787
#define ID_POPUP_WING_POSITION          32788
#define ID_POPUP_EDIT_WING              32789
#define ID_POPUP_WING_SET_POSITION      32790
#define ID_POPUP_WING_SELECT            32791
#define ID__DELETE                      32792
#define ID_POPUP_WING_DELETE            32793
#define ID__EDIT                        32794
#define ID_POPUP_ELLIPSE_EDIT           32795
#define ID_POPUP_ELLIPSE_DELETE         32796
#define ID_POPUP_ELLIPSE_POSITION       32797
#define ID_EDIT_POSITION                32798
#define ID_EDIT_DELETE                  32799
#define ID_EDIT_STRUCTURE               32800
#define ID_VIEW_PREVIEW_CUT_PATH        32801
#define ID_EDIT_PLOTFLAGS               32802
#define ID_EDIT_SELECTSTRUCTURE         32803
#define ID_POINT_NEW                    32805
#define ID_POINT_SILENT                 32806
#define ID_EDIT_PLOTORDER               32807
#define ID_FILE_CNCSETUP                32808
#define ID_FILE_CNCOUTPUT               32809
#define ID_POINT_EDIT                   32810
#define ID_EDIT_DELETESTRUCTURE         32811
#define ID_EDIT_PLOT_FLAGS              32813
#define ID_FILE_SETGRID                 32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
